const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());let scope='org:one',fail=false,items=[{id:'training:t:1',title:'Treinamento disponível',message:'Curso <script>teste</script>',date:'2026-09-19',route:'treinamentos'}];
await page.route('**/api/**',r=>r.fulfill({status:fail?503:200,json:r.request().url().includes('/api/notifications')?{ok:true,scope,items,failed:[]}:{ok:true}}));await page.goto('http://127.0.0.1:'+server.address().port);
await page.evaluate(()=>{document.body.classList.remove('auth-locked');document.body.classList.add('supervisor-mode');document.querySelector('#authScreen').hidden=true;document.querySelector('#supervisorScreen').hidden=false;});
const start=()=>page.evaluate(()=>window.LungoNotifications.start({token:'test',navigate:r=>window.selectedNotification=r}));await start();await page.waitForSelector('.supervisor-top-actions .notification-dot:not([hidden])');assert.equal(await page.locator('#supervisorPeriod').count(),0);assert.equal(await page.locator('.supervisor-top-actions label').count(),0);
await page.locator('.supervisor-top-actions .notification-trigger').click();await page.waitForSelector('.notification-row');assert.equal(await page.locator('.notification-row script').count(),0);assert.equal(await page.locator('.supervisor-top-actions .notification-dot').isVisible(),true);await page.locator('.notification-row').click();assert.equal(await page.evaluate(()=>window.selectedNotification),'treinamentos');assert.equal(await page.locator('.supervisor-top-actions .notification-dot').isVisible(),false);
await start();await page.locator('.supervisor-top-actions .notification-trigger').click();await page.waitForSelector('.notification-row');assert.equal(await page.locator('.notification-row.unread').count(),0);await page.keyboard.press('Escape');scope='org:two';await start();await page.waitForSelector('.supervisor-top-actions .notification-dot:not([hidden])');
for(const [width,height] of [[1360,633],[390,844],[320,568]]){await page.setViewportSize({width,height});const bell=await page.locator('.supervisor-top-actions .notification-trigger').boundingBox(),theme=await page.locator('#supervisorThemeBtn').boundingBox();assert.ok(bell.x+bell.width<=theme.x+1);await page.locator('.supervisor-top-actions .notification-trigger').click();const box=await page.locator('.notification-dialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width&&box.y+box.height<=height);await page.screenshot({path:path.join(root,'test-results',`notifications-${width}.png`)});await page.keyboard.press('Escape');}
await page.locator('.supervisor-top-actions .notification-trigger').click();await page.locator('.notification-read-all').click();assert.equal(await page.locator('.supervisor-top-actions .notification-dot').isVisible(),false);fail=true;await page.locator('.notification-refresh').click();await page.waitForFunction(()=>document.querySelector('.notification-status').textContent.includes('Não foi possível'));await page.evaluate(()=>window.LungoNotifications.reset());assert.equal(await page.locator('.notification-dialog').count(),0);assert.equal(await page.locator('.notification-dot:not([hidden])').count(),0);assert.deepEqual(errors,[]);console.log('Notifications: unread, read persistence, account isolation, error, reset and three viewports passed.');
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
