const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),questions=Array.from({length:8},(_,i)=>({title:'Situação comercial '+(i+1),options:['Ação A','Ação B','Ação C','Ação D']}));
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html');let source=fs.readFileSync(file,'utf8');if(file.endsWith('app.js'))source=source.replace('  const RH_STAGES =',"  window.__rh={render:data=>{recruitmentData=data;renderRecruitment();},notify:showRecruitmentNotification,save:saveRecruitmentCandidate,editEmail:openPendingCandidateEmail,restore:async()=>{supervisorAccessToken='test-only';await loadRecruitment(false,true);supervisorAccessToken='';}};\n  const RH_STAGES =");res.end(source);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());let submission;
const long='Informações detalhadas sobre a oportunidade e as atividades de vendas. '.repeat(65),vacancy={title:'Consultor comercial',headline:'Construa sua carreira',companyName:'Corretora',description:long,requirements:long,benefits:long,active:true};
await page.route('**/api/**',r=>{const u=r.request().url();if(u.includes('/complete')){submission=r.request().postDataJSON();return r.fulfill({json:{ok:true,completed:true}});}if(u.includes('/disc/'))return r.fulfill({json:{ok:true,assessmentVersion:2,commercialQuestions:questions,candidate:{name:'Pessoa Teste'},vacancy}});return r.fulfill({json:{ok:true,candidates:[],vacancy}});});
const url='http://127.0.0.1:'+server.address().port;await page.goto(url);const candidates=['novo','teste_enviado','teste_realizado','triagem','entrevista','aprovado','recusado'].map((stage,i)=>({id:'c'+i,name:i===1?'nome.muito.longo.sem.espaco@exemplo.com':'Maria Gabriela de Sobrenome Muito Comprido',stage,seenAt:'2026-09-19',city:'São Paulo',experience:'Mais de 3 anos',email:'endereco.muito.longo@exemplo.com',disc:i===1?{sentAt:'2026-09-19'}:i===2?{completedAt:'2026-09-19',result:{match:80}}:null}));
await page.evaluate(({candidates,vacancy})=>{document.body.classList.remove('auth-locked');document.body.classList.add('supervisor-mode');document.querySelector('#authScreen').hidden=true;document.querySelector('#supervisorScreen').hidden=false;document.querySelectorAll('.supervisor-view').forEach(x=>x.classList.toggle('active',x.id==='supervisor-view-rh'));window.__rh.render({vacancy,candidates});},{candidates,vacancy});fs.mkdirSync(path.join(root,'test-results'),{recursive:true});
for(const [width,height] of [[1360,633],[1169,584],[1024,768],[390,844]])for(const theme of ['dark','light']){await page.setViewportSize({width,height});await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);const failures=await page.locator('.rh-candidate-card').evaluateAll(cards=>cards.filter(card=>{const c=card.getBoundingClientRect(),l=card.closest('.rh-lane').getBoundingClientRect();return c.left<l.left||c.right>l.right+1||card.scrollWidth>card.clientWidth+1||c.height>240;}).length);assert.equal(failures,0,`cards ${width} ${theme}`);await page.screenshot({path:path.join(root,'test-results',`rh-${width}-${theme}.png`)});}
await page.setViewportSize({width:1360,height:844});
await page.evaluate(()=>window.__rh.save('c5',{hirePending:true})); assert.equal(await page.locator('[data-rh-generate-token="c5"]').count(),1);

await page.locator('[data-rh-details="c1"]').click();
await page.getByRole('button',{name:'Editar e-mail',exact:true}).click();
await page.locator('.rh-email-form input').fill('corrigido@example.com');
assert.equal(await page.getByRole('button',{name:'Reenviar teste DISC',exact:true}).isDisabled(),true);
await page.locator('.rh-email-form button[type=submit]').click();
await page.waitForFunction(()=>document.querySelector('#supervisorModalBody').textContent.includes('corrigido@example.com'));
await page.getByRole('button',{name:'Reenviar teste DISC',exact:true}).click();
await page.waitForFunction(()=>!document.querySelector('#supervisorModalBody .full button').disabled);
await page.locator('#supervisorModalCloseBtn').click();
await page.evaluate(({candidates,vacancy})=>window.__rh.render({vacancy,candidates:[...candidates,{id:'hired',name:'João Aprovado',email:'joao@example.com',phone:'11999998888',stage:'aprovado',hiredUserId:'broker',approvedAt:'2026-09-19T10:00:00Z',accessGrantedAt:'2026-09-20T10:00:00Z'}]}),{candidates,vacancy});
assert.equal(await page.locator('[data-rh-candidate="hired"]').count(),0);
await page.locator('#rhApprovedTab').click();
for(const query of ['joao','joao@example.com','(11) 99999-8888']){await page.locator('#rhApprovedSearch').fill(query);assert.equal(await page.locator('#rhApprovedList tbody tr').count(),1);}
await page.locator('#rhApprovedSearch').fill('inexistente');assert.equal(await page.locator('#rhApprovedList tbody tr').count(),0);
await page.locator('#rhSelectionTab').click();
await page.evaluate(c=>window.__rh.notify(c),candidates[2]);assert.match(await page.locator('#rhCandidateNotification h2').innerText(),/respondeu ao teste DISC/);await page.locator('#rhNotificationClose').click();await page.waitForSelector('#rhCandidateNotification',{state:'detached'});await page.evaluate(c=>window.__rh.notify(c),candidates[0]);assert.match(await page.locator('#rhCandidateNotification h2').innerText(),/Novo candidato/);
await page.route('**/api/supervisor/recruitment', r=>r.fulfill({json:{ok:true,vacancy,candidates:[{id:'persisted',name:'Aguardando plano',stage:'aprovado',hirePending:true,email:'pendente@example.com',seenAt:'2026-09-20'}]}}));
await page.reload(); await page.evaluate(()=>window.__rh.restore());
assert.equal(await page.locator('[data-rh-generate-token="persisted"]').count(),1);
assert.equal(await page.locator('[data-rh-delete-pending="persisted"]').count(),1);
assert.equal(await page.locator('[data-rh-pending-email="persisted"]').count(),1);
await page.evaluate(()=>window.__rh.editEmail({id:'persisted',email:'pendente@example.com'}));
await page.locator('#rhPendingEmailModal input').fill('novo@example.com');
await page.locator('#rhPendingEmailModal [type=submit]').click();
await page.waitForFunction(()=>!document.querySelector('#rhPendingEmailModal').open);
assert.match(await page.locator('.pending-hire-row').innerText(),/novo@example.com/);

await page.goto(url+'/?vaga=teste');await page.waitForFunction(()=>document.querySelector('#publicVacancyDescription').textContent.length>1000);
for(const width of [1360,1024,768,390,320])for(const theme of ['dark','light']){await page.setViewportSize({width,height:844});await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);const geometry=await page.locator('.public-application-form').evaluate(x=>({height:x.getBoundingClientRect().height,scroll:x.scrollWidth,client:x.clientWidth,bg:getComputedStyle(x.querySelector('input')).backgroundColor}));assert.ok(geometry.height<950&&geometry.scroll<=geometry.client+1,JSON.stringify({width,geometry}));assert.equal(geometry.bg,'rgb(247, 250, 251)');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>scrollTo(0,0)); await page.mouse.move(width/2,400); await page.mouse.wheel(0,100000); await page.waitForFunction(()=>scrollY>0 && innerHeight+scrollY>=document.documentElement.scrollHeight-2); assert.ok(await page.evaluate(()=>scrollY>0 && innerHeight+scrollY>=document.documentElement.scrollHeight-2), 'Landing must scroll to the bottom'); await page.screenshot({path:path.join(root,'test-results',`vacancy-${width}-${theme}.png`)});}
await page.goto(url+'/disc-demo.html?token=test');await page.waitForFunction(()=>!document.querySelector('#startBtn').disabled);await page.locator('#startBtn').click();for(let i=0;i<12;i++){await page.locator('[data-choice=most][data-option="0"]').click();await page.locator('[data-choice=least][data-option="1"]').click();await page.locator('#nextBtn').click();}assert.match(await page.locator('.choice-guide').innerText(),/Escolha a ação/);for(let i=0;i<8;i++){await page.locator('.commercial-choice').nth(i%4).click();await page.locator('#nextBtn').click();}await page.waitForFunction(()=>!document.querySelector('#submitted').hidden);assert.equal(submission.answers.length,12);assert.equal(submission.commercialAnswers.length,8);assert.equal(submission.assessmentVersion,2);assert.deepEqual(errors,[]);console.log('RH: eight kanban variants, ten long-content landing variants, notifications and version-2 assessment passed.');
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
